version: "3.5"

services:
    influxdb:
        image: telegraf-secs:20230228
        container_name: solaredge-scraper
        restart: always
        user: "1024:1000"
        command: [
            "telegraf", 
            "--config",  
            "/etc/telegraf/telegraf.conf", 
            "--config-directory",
            "/etc/telegraf/telegraf.d"
        ]
        volumes:
            - type: bind
              source: ./settings.py
              target: /var/lib/telegraf/settings.py
              read_only: true
            - type: bind
              source: ./telegraf.conf
              target: /etc/telegraf/telegraf.conf
              read_only: true
